### ISSUE TITLE
Updating for v5

### ISSUE THREAD

**Issue by Gesma94** [fastify/forwarded#62]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

👋 I'm Matteo, and would like to work on this.
Coming from Fastify issue #5116 (https://github.com/fastify/fastify/issues/5116)

From what I've understood, I need to:
- Update NPM packages (`standard`, `tap`, `@types/node`)
- Update the workflow to use the version 4.1.0 of `plugins-ci`

If there's anything I'm missing, please do let me know

**Comment by Gesma94** [comment]
I'm sorry to bother, but can I have the `next` branch created?

**Comment by jsumners** [comment]
@Gesma94 thank you for you patience. The `next` branch has now been created.

**Comment by Gesma94** [comment]
As soon as I have some spare minutes, I'll look into this. I think I already have the changes on a forked branch.

**Comment by Fdawgs** [comment]
Closed by #63
